feat: add auto-generated header to generated files
NordSecurity/uniffi-bindgen-cs pull request #56
Opened 2023-11-24 14:26 UTC by meenzen

closes #25

2023-11-27 08:57 UTC, arg0d requested changes
I see warnings in generated test code after adding auto generated annotation.
> _The annotation for nullable reference types should only be used in code within a '#nullable' annotations context. Auto-generated code requires an explicit '#nullable' directive in source._

I guess it should also be fixed?

2023-11-27 08:57 UTC, arg0d commented on bindgen/src/lib.rs
> +            r#"// <auto-generated>
It feels like this should be part of [Wrapper.cs](https://github.com/NordSecurity/uniffi-bindgen-cs/blob/main/bindgen/templates/wrapper.cs). `CARGO_PKG_VERSION` can be added as `version` to `CsWrapper` struct, and accessed from the template using `{{ version }}`.

2023-11-27 09:36 UTC, meenzen commented
Having the header in wrapper.cs may make it harder to implement code formatting in the future, that's why I added this comment:

```cs
// Formatting must be done before the auto-generated header is added, otherwise the formatting tool will ignore the file.
```

2023-11-27 11:19 UTC, arg0d commented
I see your point, but until formatting is implemented this looks very weird. I'm not familliar with C# formatting tools, but I would hope its possible to format an auto generated file.

2023-11-27 11:23 UTC, arg0d commented
Oops, I somehow missed https://github.com/NordSecurity/uniffi-bindgen-cs/issues/55. Will take a quick look at the tool, maybe its psosible to format generated file.

2023-11-27 11:46 UTC, arg0d commented
Looking at CSharpier code, its not possible to bypass the `auto-generated` guard. While you are at this, could you just implement the formatting using CSharpier? Its quite trivial, and it would clear up the reason why `auto-generated` is not in `wrapper.cs`.

[Formatting example from Kotlin](https://github.com/mozilla/uniffi-rs/blob/9f7c3c4663f024adff9c7b60fc3572a36a6eb136/uniffi_bindgen/src/bindings/kotlin/mod.rs#L28C10-L33C10).

2023-11-27 12:12 UTC, arg0d commented
Formatting should be CLI option as well like in `mozilla/uniffi-rs` generators, in case the user does not have csharpier installed, or simply does not wish to format the file.

2023-11-27 14:17 UTC, meenzen commented
Formatting is now implemented, but I'm not sure how to add the cli option. This is my first ever rust pr so I have no idea what I'm doing. Could you point me in the right direction?

2023-11-28 11:03 UTC, meenzen commented
Sould I squash the commits and remove the changes to `Cargo.lock` and the `.gitignore` that snuck in?

2023-11-28 11:54 UTC, merged